cd/apps/galeria/urls.py
__author__ = 'Ronald'
from django.conf.urls import patterns, include, url
from .views import *
from django.conf import settings


urlpatterns = patterns('',
                       url(r'^BaseGaleria$', BaseGaleria.as_view(), name='base-galeria'),
                       url(r'^Categoria/$', Categoria_Album.as_view(), name='cat-album'),
                       url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                       url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
                       url(r'^Categoria/(?P<pk>\d+)/Detalle/$', Categoria_detalle.as_view(), name='cat-detalle'),
                       url(r'^ListaFotos/$', ListaFotos.as_view(), name='lista-fotos'),
                       url(r'^Foto/(?P<pk>\d+)/Detalle/$', FotoDetalle.as_view(), name='foto-detalle'),
                       url(r'^Actualizar/(?P<pk>\d+)/Foto/$', ActualizarFoto.as_view(), name='actualizar-foto'),
                       url(r'^SubirFoto/$', SubirFoto.as_view(), name='subir-foto'),
                       url(r'^SubirCategoria/$', SubirCategoria.as_view(), name='subir-categoria'),
                       url(r'^Borrar/(?P<pk>\d+)/Foto/$', BorrarFoto.as_view(), name='borrar-foto'),

)

cd/apps/inicio/urls.py
__author__ = 'Ronald'
from django.conf.urls import include, url
from .views import *

urlpatterns = [
    url(r'^base$', index.as_view(), name='base'),
    url(r'^$', 'django.contrib.auth.views.login',
        {'template_name':'inicio/login.html'}, name='login'),
    url(r'^cerrar$', 'django.contrib.auth.views.logout_then_login',
        name='logout'),
    url(r'^registro/$', UserCreateView.as_view(), name='reg'),
	url(r'^activar/(?P<codigo>.+)/$', ActivteUserView.as_view(), name='activar_user'),
	url(r'^activo/$', UserActiveErrorView.as_view(), name='activo'),
	url(r'^activo_exito/$', UserActiveView.as_view(), name='exito_activo'),
    url(r'^error_activacion/$', ErrorActiveView.as_view(), name='error_activacion'),

]

cd/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include("cd.apps.inicio.urls")),
    url(r'^galeria/', include('cd.apps.galeria.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
]

cd/apps/galeria/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.core.urlresolvers import reverse
from django.dispatch import receiver
from django.contrib.auth.models import User



class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

    def __unicode__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('cat-album')    


class Fotos(models.Model):
    """ Fotos del album """

    categoria = models.ForeignKey(Categoria, null=True, blank=True)
    titulo = models.CharField(max_length=50, default='No title')
    foto = models.ImageField(upload_to='Galeria/')
    fecha = models.DateField(auto_now_add=True)
    favorito = models.BooleanField(default=False)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('lista-fotos')


@receiver(post_delete, sender=Fotos)
def foto_delete(sender, instance, **kwargs):
    """ Borra los ficheros de las fotos que se eliminan. """
    instance.foto.delete(False)

class Comentario(models.Model):
    foto = models.ForeignKey(Fotos)
    contenido = models.TextField()
    fecha = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return self.contenido

    def get_absolute_url(self):
        return reverse('lista-fotos',args=[str(self.id)])
    

cd/apps/inicio/models.py
from django.db import models
from django.contrib.auth.models import User

User.add_to_class('act', models.CharField(max_length=30,null=True))

cd/apps/galeria/forms.py
__author__ = 'Ronald'

from django import forms
from .models import Comentario

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['contenido']

cd/apps/inicio/forms.py
# -*- coding: UTF-8 -*-
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django import forms
from django.contrib.auth.models import User
from captcha.fields import ReCaptchaField
import re

class UserForm(UserCreationForm):
	password1 = forms.CharField(
        label='Clave',
        widget=forms.PasswordInput()
    )
	password2 = forms.CharField(
        label='Ingrese su clave nuevamente',
        widget=forms.PasswordInput()
    )
	username = forms.CharField(label = "Nombre de Usuario")
	email = forms.EmailField(label = "Email")
	first_name = forms.CharField(label = "Nombres")
	last_name = forms.CharField(label = "Apellidos")
	captcha = ReCaptchaField(attrs={'theme' : 'clean'})

	class Meta:
		model = User
		fields = ("username", "first_name","last_name", "email", "password1", "password2","captcha")


	def clean_password2(self):
		"""
		Revisar que ambas claves dadas coincidan
		"""
		if 'password1' in self.cleaned_data:
			password = self.cleaned_data['password1']
			password_che = self.cleaned_data['password2']
                if password == password_che:
                        return password_che
                raise forms.ValidationError('Claves no coinciden.')


        def clean_email(self):
        	"""
        		Validar que la direccion de correos dada sea unica en el proyecto
        	"""
        	if User.objects.filter(email__iexact=self.cleaned_data['email']).count():
        		raise forms.ValidationError(u'Esta dirección de correos esta en uso, por favor utilice otra')
        	return self.cleaned_data['email']

cd/apps/galeria/views.py
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.core.urlresolvers import reverse_lazy
from .models import *
from .forms import *
from django.http import Http404
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout,authenticate

# Create your views here.

class BaseGaleria(TemplateView):
    template_name = 'BaseGaleria.html'

class Categoria_Album(ListView):
    model = Categoria
    template_name = 'galeria/categoria.html'

class Categoria_detalle(DetailView):
    model = Categoria
    template_name = 'galeria/CategoriaDetalle.html'


class ListaFotos(ListView ):
    model = Fotos
    template_name = 'galeria/ListaFotos.html'


class FotoDetalle(DetailView):
    model = Fotos
    template_name = 'galeria/FotoDetalle.html'

    def get_context_data(self, **kwargs):
        context = super(FotoDetalle, self).get_context_data(**kwargs)
        context['form'] = ComentarioForm()
        return context

    def post(self, request,  *args, **kwargs):
        id=self.get_object().id
        if(request.method=="POST"):
            comentario=ComentarioForm(request.POST.copy())
            comentario.instance.user = self.request.user
            comentario.instance.foto = self.get_object()
            comentario.data['foto'] = self.get_object().id
            comentario.data['user'] = self.get_object().id
            if(comentario.is_valid()):
                comentario.save()
                return HttpResponseRedirect('/galeria/ListaFotos')

class ActualizarFoto(UpdateView):
    model = Fotos
    fields = ['categoria', 'titulo', 'foto', 'favorito', 'user']
    template_name = 'galeria/SubirActualizarFoto.html'

class SubirFoto(CreateView):
    model = Fotos
    fields = ['categoria', 'titulo', 'foto', 'favorito', 'user']
    template_name = 'galeria/AgregarFoto.html'

class SubirCategoria(CreateView):
    model = Categoria
    fields = ['nombre']
    template_name = 'galeria/AgregarCategoria.html'    

class BorrarFoto(DeleteView):
    model = Fotos
    success_url = reverse_lazy('lista-fotos')
    template_name = 'galeria/BorrarFoto.html'

cd/apps/inicio/views.py
# -*- coding: UTF-8 -*-
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from .forms import *
from django.core.urlresolvers import reverse_lazy
from django.views.generic import FormView, TemplateView, CreateView, View
from .models import *
from django.core.mail import EmailMultiAlternatives
import random, string
from django.contrib.auth.models import User



class index(TemplateView):
    template_name = 'base.html'

class ErrorActiveView(TemplateView):
    template_name = 'inicio/error_activacion.html'
    
class UserActiveErrorView(TemplateView):
    template_name = 'inicio/usuario_ya_activo.html'

class UserActiveView(TemplateView):
    template_name = 'inicio/usuario_activo.html'


class UserCreateView(CreateView):
    model = User
    form_class = UserForm
    template_name = 'inicio/register.html'
    
    def form_valid(self, form):
        form.instance.is_active = False
        form.instance.act = ''.join(random.choice(string.ascii_uppercase + string.digits)
                                               for n in range(20))
        usuario = form.cleaned_data.get('email')
        html_content = 'Por favor visite http://127.0.0.1:8000/activar/%s/ para activar su cuenta' \
                       %(form.instance.act)
        msg = EmailMultiAlternatives('Código de Activación',html_content,\
                                     'friends_77_3@hotmail.com',[usuario])
        msg.attach_alternative(html_content,'text/html') # Definimos el contenido como HTML
        msg.send() # Enviamos el correo
        return super(UserCreateView, self).form_valid(form)


class ActivteUserView(View):
    
    def dispatch(self, *args, **kwargs):
        self.codigo = self.kwargs['codigo']
        return super(ActivteUserView, self).dispatch(*args, **kwargs)
        
    def get(self, request, *args, **kwargs):
        try:
            self.usuario = User.objects.get(act=self.codigo)
            if self.usuario.is_active == False:
                self.usuario.is_active = True
                self.usuario.save()
                return HttpResponseRedirect("/activo_exito/")
            else:
                return HttpResponseRedirect("/activo/")
        except UserRegister.DoesNotExist:
            return HttpResponseRedirect('/error_activacion')

cd/apps/perfildeorganizacion/views.py
from django.shortcuts import render

# Create your views here.

cd/templates/galeria/AgregarCategoria.html
{% extends 'BaseGaleria.html' %}

{% block section %}
    <h2>Agregar Categoria</h2>
    <hr>
{% endblock section %}

{% block maincontent %}
    <form enctype="multipart/form-data" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
        <a class='btn' href="{% url 'lista-fotos' %}">Cancel</a>
    </form>
{% endblock maincontent%}

cd/templates/galeria/AgregarFoto.html
{% extends 'BaseGaleria.html' %}

{% block section %}
    <h2>Agregar Foto</h2>
    <hr>
{% endblock section %}

{% block maincontent %}
    <form enctype="multipart/form-data" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
        <a class='btn' href="{% url 'lista-fotos' %}">Cancel</a>
    </form>
{% endblock maincontent%}

cd/templates/galeria/BorrarFoto.html
{% extends 'BaseGaleria.html' %}
{% load static %}

{% block maincontent %}
    <form action="" method="post">{% csrf_token %}
        <p><h4>Esta Seguro de Eliminar => "{{ object.titulo }}" ?</h4></p>
        <img src="{% static object.foto.url %}" style="width:550px;height:420px"/>
        <input type="submit" value="Confirmar" />
        <a class='btn' href="{% url 'lista-fotos' %}">Cancel</a>
    </form>
{% endblock maincontent %}

cd/templates/galeria/CategoriaDetalle.html
{% extends 'BaseGaleria.html' %}
{% load static %}

{% block section %}
    <h2>{{ object.nombre }}</h2>
    <hr>
{% endblock section %}

{% block maincontent %}
<div>
    <table border="1px">
        <tr>
            {% for p in object.fotos_set.all %}

                <div class="col-lg-2">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            {{ p.titulo }}
                        </div>
                        <div class="panel-body">
                            <a href="{% url "foto-detalle" p.id %}">
                            <img class="img-thumbnail"  src="{% static p.foto.url %}" style="width:190px;height:200px"/>
                        </div>
                    </div>
                </div>


            {% endfor %}
        </tr>
    </table>
</div>
{% endblock maincontent %}

cd/templates/galeria/FotoDetalle.html
{% extends 'BaseGaleria.html' %}
{% load static %}


{% block section %}
    <h2>
        {% if object.categoria_id %}
            ( <a href="{% url "cat-detalle" object.categoria_id %}">{{ object.categoria }}</a> )
        {% endif %}
    </h2>
    <hr>
{% endblock section %}

{% block maincontent %}
<div>

    <div class="col-lg-8">
        <div class="panel panel-info">
            <div class="panel-heading">
            <h2>
                {{ object.titulo }}
                {% if object.favorito %}
                    &#9733;
                {% else %}
                    &#9734;
                {% endif %}
            </h2>

                <a href="{% url "actualizar-foto" object.id %}">Editar</a>
                <a href="{% url "borrar-foto" object.id %}">Eliminar</a>
            </div>
            <div class="panel-body">
                <img src="{% static object.foto.url %}"  style="width:550px;height:420px"/>
            </div>
        </div>
    </div>
    <div class="col-lg-8">
        <div class="panel panel-info">
            <div class="panel-heading">
            <h3>
                    comentarios
            </h3>
            </div>
            <form action="" method="post">{%csrf_token%}
                <div class="panel-body">
                    <textarea class="form-control" id="id_contenido" name="contenido" rows="3"></textarea>
                    <input type="submit" value="enviar"/>
                </div>
                <div class="panel-body">
                    {% for p in object.comentario_set.all %}
                        <div >
                                {{ p.user }}=>
                                {{ p.contenido }}
                        </div>
                    {% endfor %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock maincontent %}

cd/templates/galeria/ListaFotos.html
{% extends 'BaseGaleria.html' %}

{% load static %}

{% block section %}
    <h2>Fotos</h2>
    <hr>
{% endblock section %}

{% block maincontent %}
    <div class="row well">
        {% for p in object_list.all %}
            <div class="col-md-4 well">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ p.titulo }}</h3>
                    </div>
                    <div class="panel-body">
                            <a href="{% url "foto-detalle" p.id %}">
                            <img class="img-responsive"  src="{% static p.foto.url %}"  style="width:200px;height:200px;"/>
                        </a>
                    </div>
                    <div class="panel-footer">
                        {% if p.comment %}
                            {{ p.comment }}
                        {% else %}
                            <a href="{% url "actualizar-foto" p.id %}">Modificar</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock maincontent %}

cd/templates/galeria/SubirActualizarFoto.html
{% extends 'BaseGaleria.html' %}

{% block maincontent %}
    <form enctype="multipart/form-data" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
        <a class='btn' href="{% url 'lista-fotos' %}">Cancel</a>
    </form>
{% endblock maincontent%}

cd/templates/galeria/categoria.html
{% extends 'BaseGaleria.html' %}

{% block section %}
    <h2>Category</h2>
    <hr>
{% endblock section %}

{% block maincontent %}
    <div>
        {% for c in object_list %}
            <a href="{% url 'cat-detalle' c.pk %}">
            <ul>
            <span class="glyphicon glyphicon-book"></span>
            <button type="button" class="btn btn-primary btn-xs">{{ c.nombre }}	</button>
            </ul>
            </a>
        {% endfor %}
    </div>
{% endblock maincontent %}